//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 6/1/2016 1:36:02 AM
namespace VisaPortal.ServiceDOLSummerJobs
{
    
    /// <summary>
    /// There are no comments for SummerJobsCall in the schema.
    /// </summary>
    public abstract partial class SummerJobsCall : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new SummerJobsCall object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SummerJobsCall(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        public abstract void OnContextCreated();
    }
}
