//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 5/31/2016 10:06:20 PM
namespace VisaPortal.ServiceDOLAgency
{
    
    /// <summary>
    /// There are no comments for AgencyEntities in the schema.
    /// </summary>
    public partial class AgencyEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new AgencyEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public AgencyEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "AgencyModel", "VisaPortal.ServiceDOLAgency");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("VisaPortal.ServiceDOLAgency", global::System.StringComparison.Ordinal))
            {
                return string.Concat("AgencyModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Agencies in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Agencies> Agencies
        {
            get
            {
                if ((this._Agencies == null))
                {
                    this._Agencies = base.CreateQuery<Agencies>("Agencies");
                }
                return this._Agencies;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Agencies> _Agencies;
        /// <summary>
        /// There are no comments for Agencies in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAgencies(Agencies agencies)
        {
            base.AddObject("Agencies", agencies);
        }
    }
    /// <summary>
    /// There are no comments for AgencyModel.Agencies in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Agency
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Agency")]
    public partial class Agencies
    {
        /// <summary>
        /// Create a new Agencies object.
        /// </summary>
        /// <param name="agency">Initial value of Agency.</param>
        /// <param name="agencyFullName">Initial value of AgencyFullName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Agencies CreateAgencies(string agency, string agencyFullName)
        {
            Agencies agencies = new Agencies();
            agencies.Agency = agency;
            agencies.AgencyFullName = agencyFullName;
            return agencies;
        }
        /// <summary>
        /// There are no comments for Property Agency in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Agency
        {
            get
            {
                return this._Agency;
            }
            set
            {
                this.OnAgencyChanging(value);
                this._Agency = value;
                this.OnAgencyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Agency;
        partial void OnAgencyChanging(string value);
        partial void OnAgencyChanged();
        /// <summary>
        /// There are no comments for Property AgencyFullName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AgencyFullName
        {
            get
            {
                return this._AgencyFullName;
            }
            set
            {
                this.OnAgencyFullNameChanging(value);
                this._AgencyFullName = value;
                this.OnAgencyFullNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AgencyFullName;
        partial void OnAgencyFullNameChanging(string value);
        partial void OnAgencyFullNameChanged();
        /// <summary>
        /// There are no comments for Property WebsiteURL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WebsiteURL
        {
            get
            {
                return this._WebsiteURL;
            }
            set
            {
                this.OnWebsiteURLChanging(value);
                this._WebsiteURL = value;
                this.OnWebsiteURLChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WebsiteURL;
        partial void OnWebsiteURLChanging(string value);
        partial void OnWebsiteURLChanged();
        /// <summary>
        /// There are no comments for Property MissionURL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MissionURL
        {
            get
            {
                return this._MissionURL;
            }
            set
            {
                this.OnMissionURLChanging(value);
                this._MissionURL = value;
                this.OnMissionURLChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MissionURL;
        partial void OnMissionURLChanging(string value);
        partial void OnMissionURLChanged();
        /// <summary>
        /// There are no comments for Property OrganizationalURL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OrganizationalURL
        {
            get
            {
                return this._OrganizationalURL;
            }
            set
            {
                this.OnOrganizationalURLChanging(value);
                this._OrganizationalURL = value;
                this.OnOrganizationalURLChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OrganizationalURL;
        partial void OnOrganizationalURLChanging(string value);
        partial void OnOrganizationalURLChanged();
        /// <summary>
        /// There are no comments for Property KeyPersonnelURL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string KeyPersonnelURL
        {
            get
            {
                return this._KeyPersonnelURL;
            }
            set
            {
                this.OnKeyPersonnelURLChanging(value);
                this._KeyPersonnelURL = value;
                this.OnKeyPersonnelURLChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _KeyPersonnelURL;
        partial void OnKeyPersonnelURLChanging(string value);
        partial void OnKeyPersonnelURLChanged();
    }
}
